# Generated by Django 4.0.3 on 2023-03-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_appointments_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician', models.CharField(max_length=50)),
                ('employee_no', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
