# Generated by Django 4.0.3 on 2023-03-08 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_remove_automobilevo_color_remove_automobilevo_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technician',
            old_name='technician',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician', to='service_rest.technician'),
        ),
    ]
