# Generated by Django 4.0.3 on 2023-03-08 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_rename_technician_technician_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='vin',
        ),
        migrations.AddField(
            model_name='appointments',
            name='vehicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='service_rest.automobilevo'),
        ),
    ]
