# Generated by Django 4.0.3 on 2023-03-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_remove_appointments_vin_appointments_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
