# Generated by Django 4.0.3 on 2023-03-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0008_alter_appointments_date_alter_appointments_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
