# Generated by Django 4.0.3 on 2023-03-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0009_appointments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='vip',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
