# Generated by Django 4.0.3 on 2023-03-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0010_appointments_vip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='status',
            new_name='completion',
        ),
    ]
