# Generated by Django 4.0.3 on 2023-03-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0011_rename_status_appointments_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='appointments',
            name='vin',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
    ]
