# Generated by Django 4.0.3 on 2023-03-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0012_remove_appointments_vehicle_appointments_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='vin',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
